### ISSUE TITLE
@ symbol is missing in styles

### ISSUE THREAD

**Issue by alexanderyarm** [vudash/vudash#36]
After removing `node_modules` folder and installing all dependencies again, CSS animation doesn't work in my widget.

After investigation i found out that @ symbol is removed from beginning of animation declaration 
![screen shot 2017-07-17 at 11 31 17](https://user-images.githubusercontent.com/2443817/28262625-f7c7d7e0-6ae3-11e7-8f01-76d8c0609c79.png)

it has to be `@keyframes ...`

**Comment by antony** [comment]
are you running a cloned version of the repository, or are you running `v7.7.0`?

I've been doing some refactoring to make the code more readable and it's possible that I deleted this by accident!

**Comment by antony** [comment]
What widget is this @alexanderyarm ? I can't find any reference to `achtung`, `#750000` nor any missing `@keyframes` in the codebase?

What version are you using?

**Comment by alexanderyarm** [comment]
@antony sorry for long answer
currently i'm using vudash version `7.6.3`. This is code from widget i wrote by myself. It's not on github. It's only exists locally on my pc.

The problem is that it worked perfect until i removed `node_modules` and install dependencies again. After it symbol `@` which exists in code is not there when i'm trying to debug it with chrome dev tools.

**Comment by antony** [comment]
This sounds a lot like a problem with rollup, actually.

Try upgrading to v7.7.0 as it has new rollup/babel versions and see if this helps. Don't forget to delete node_modules again.

If it persists, I can try to replicate it and figure out where the bug is coming from.It might be svelte, rollup, or rollup-babel.

**Comment by antony** [comment]
I've raised an issue with svelte (as I was able to replicate it in their REPL) here https://github.com/sveltejs/svelte/issues/712

**Comment by alexanderyarm** [comment]
Thanks a lot for handling this issue

**Comment by antony** [comment]
This has been fixed in https://github.com/sveltejs/svelte/issues/712

I've upgraded svelte and released vudash@7.8.2 - give it a go @alexanderyarm!

**Comment by antony** [comment]
Unfortunately this brought with it another svelte issue I've fixed in v7.8.3 (I hope) https://github.com/sveltejs/svelte/issues/722

Use rgb(...) notation for colours rather than #xxx and you should be fine until this is fixed.

Here's a nice site I used to convert all mine over! https://www.webpagefx.com/web-design/hex-to-rgb/
