### ISSUE TITLE
Allow external resolution of dashboard config

### ISSUE THREAD

**Issue by ccollie** [vudash/vudash#43]
It would be useful to have an extension point to load dashboards from an external source. I'd like to add and updates dashboards without a redeploy.

**Comment by antony** [comment]
Interesting - I'm pretty sure this is workable. I'm not sure how it would work if you updated a dashboard, since the UI gets hold of a bunch of autogenerated ids and it would have to somehow autodestroy and autorecreate those.

How do you imagine auto-detection working? An api endpoint to call, or file watching?

**Comment by antony** [comment]
@ccollie Vudash now has an API. How do you feel about being able to POST / PUT dashboard configuration to it?

**Comment by ccollie** [comment]
Works for me.

**Comment by antony** [comment]
@ccollie https://vudash.com/#/api/?id=put-apiv1dashboardsname
