### ISSUE TITLE
Trigger client reload on dashboard restart/reconnect

### ISSUE THREAD

**Issue by Dbzman** [vudash/vudash#51]
Hey there,

we have vudash running on a Raspberry PI connected to a TV. (kiosk mode)
This works pretty nice so far. However the connection gets lost from time to time (due to dashboard server restarts or deployments of a new dashboard version). This means we need to refresh the browser manually.
It would be really great to have a page reload triggered whenever a new connection was made after the connection has been lost.

Cheers

**Comment by antony** [comment]
Agreed - I have noticed the same thing.

I'll add this to the roadmap. But I've just added in > 9.1.0 an api endpoint for reloading/changing the current dashboard. You could possibly add this into a build process, or just hit it manually rather than have to do a manual refresh.

Let me know what you think and i'll work on this functionality :)

**Comment by antony** [comment]
Fixed in v9.2.1 :) Enjoy

You can configure the reload timeout by passing environment variable `DISCONNECT_RELOAD_TIMEOUT` - i've set it to 30 seconds by default.

**Comment by Dbzman** [comment]
Wow, this works great. Thank you very much! 👍
